# OpenFGA Sync Service - Example Configuration
# This file demonstrates all available configuration options

# Server configuration for health/metrics endpoints
server:
  port: 8080

# OpenFGA instance configuration
openfga:
  endpoint: "https://api.openfga.example.com"  # OpenFGA API endpoint
  store_id: "01HXXX-EXAMPLE-STORE-ID"          # Your OpenFGA store ID
  token: "fga_secret_token_here"               # Optional: API token for authentication
  
  # OIDC authentication configuration (alternative to token)
  # Use this for Auth0 FGA or other OIDC-enabled OpenFGA instances
  oidc:
    issuer: "https://your-auth0-domain.auth0.com/"          # OIDC issuer URL
    audience: "https://api.us1.fga.dev/"                    # API audience 
    client_id: "your-client-id"                             # Client credentials ID
    client_secret: "your-client-secret"                     # Client credentials secret
    scopes: ["read:tuples", "write:tuples"]                 # Optional: specific scopes
    token_issuer: "https://your-auth0-domain.auth0.com/"    # Token issuer (usually same as issuer)

# Backend storage configuration
backend:
  type: "postgres"                             # Storage type: postgres, mysql, sqlite
  dsn: "postgres://user:password@localhost:5432/openfga_sync?sslmode=disable"
  mode: "changelog"                            # Storage mode: changelog or stateful

# Example configurations for different backends:
# 
# PostgreSQL:
#   type: "postgres"
#   dsn: "postgres://user:password@localhost:5432/openfga_sync?sslmode=disable"
#   mode: "changelog"
#
# SQLite (file-based):
#   type: "sqlite"
#   dsn: "/var/lib/openfga-sync/data.db"
#   mode: "stateful"
#
# SQLite (in-memory for testing):
#   type: "sqlite"
#   dsn: ":memory:"
#   mode: "changelog"
#
# OpenFGA (replication to another OpenFGA instance):
#   type: "openfga"
#   dsn: "http://target-openfga:8080/target-store-id"
#   mode: "stateful"
#
# MySQL (coming soon):
#   type: "mysql"
#   dsn: "user:password@tcp(localhost:3306)/openfga_sync?parseTime=true"
#   mode: "changelog"

# Logging configuration
logging:
  level: "info"                                # Log level: debug, info, warn, error, fatal, panic
  format: "json"                               # Log format: text or json

# Observability and monitoring
observability:
  opentelemetry:
    endpoint: "http://otel-collector:4317"     # OpenTelemetry collector endpoint
    service_name: "openfga-sync"               # Service name for tracing
    enabled: true                              # Enable OpenTelemetry tracing
  metrics:
    enabled: true                              # Enable Prometheus metrics
    path: "/metrics"                           # Metrics endpoint path

# Service behavior configuration  
service:
  poll_interval: "5s"                          # How often to poll for changes
  batch_size: 100                              # Maximum changes to process per batch
  max_retries: 3                               # Maximum retry attempts on failure
  retry_delay: "1s"                            # Delay between retry attempts
  max_changes: 0                               # Maximum changes to fetch (0 = no limit)
  request_timeout: "30s"                       # Timeout for individual OpenFGA requests
  max_retry_delay: "5s"                        # Maximum delay between retries
  backoff_factor: 2.0                          # Exponential backoff multiplier
  rate_limit_delay: "50ms"                     # Delay between requests for rate limiting
  enable_validation: true                      # Enable change event validation

# Kubernetes leader election (for HA deployments)
leadership:
  enabled: true                                # Enable leader election
  namespace: "openfga-system"                  # Kubernetes namespace for the lock
  lock_name: "openfga-sync-leader"             # Name of the leader lock

---
# Environment Variable Examples:
# 
# OPENFGA_ENDPOINT=https://api.openfga.example.com
# OPENFGA_STORE_ID=01HXXX-EXAMPLE-STORE-ID
# OPENFGA_TOKEN=fga_secret_token_here
# BACKEND_TYPE=postgres
# BACKEND_DSN=postgres://user:password@localhost:5432/openfga_sync?sslmode=disable
# BACKEND_MODE=changelog
# 
# For SQLite:
# BACKEND_TYPE=sqlite  
# BACKEND_DSN=/var/lib/openfga-sync/data.db
# BACKEND_MODE=stateful
#
# For OpenFGA replication:
# BACKEND_TYPE=openfga
# BACKEND_DSN=http://target-openfga:8080/target-store-id
# BACKEND_MODE=stateful
# LOG_LEVEL=info
# LOG_FORMAT=json
# OTEL_ENDPOINT=http://otel-collector:4317
# OTEL_SERVICE_NAME=openfga-sync
# OTEL_ENABLED=true
# METRICS_ENABLED=true
# METRICS_PATH=/metrics
# POLL_INTERVAL=5s
# BATCH_SIZE=100
# MAX_RETRIES=3
# RETRY_DELAY=1s
# MAX_CHANGES=0
# REQUEST_TIMEOUT=30s
# MAX_RETRY_DELAY=5s
# BACKOFF_FACTOR=2.0
# RATE_LIMIT_DELAY=50ms
# ENABLE_VALIDATION=true
# LEADERSHIP_ENABLED=true
# LEADERSHIP_NAMESPACE=openfga-system
# LEADERSHIP_LOCK_NAME=openfga-sync-leader
