server:
  port: 8080

openfga:
  endpoint: "http://localhost:8080"
  store_id: "01HVMM0T3RQDNG2KQYX4RTKJ95"
  token: "test-token"

backend:
  type: "sqlite"
  dsn: ":memory:"
  mode: "changelog"

logging:
  level: "info"
  format: "text"

observability:
  opentelemetry:
    enabled: false
  metrics:
    enabled: false

service:
  poll_interval: "60s"
  batch_size: 10
  max_retries: 1
  retry_delay: "1s"

leadership:
  enabled: false
